### ISSUE TITLE
 arfoundation-samples + InputSystem package = error

### ISSUE THREAD

**Issue by JustKoTMurchik** [Unity-Technologies/arfoundation-samples#555] opened 2020-07-22 06:20 UTC
1. Download  arfoundation-samples.
2. Install Input System package.
3. Error.

Unity 2019.4.4f1
![Screenshot_1](https://user-images.githubusercontent.com/36777391/88141583-8f9f4b80-cbfc-11ea-87dc-7a6f6c0d605d.png)

**Comment by tdmowrer** [comment] 2020-07-22 16:48
Looks like a regression with the latest preview packages. If you use the verified 4.0.x packages, you should not have a problem.

**Comment by kjyv** [comment] 2020-07-22 17:43
We have this issue too, it only appeared with 4.1.0-preview.5

**Comment by tdmowrer** [comment] 2020-07-28 17:07
This has been fixed in the `com.unity.xr.arcore@4.1.0-preview.6` package (now available).

**Closed by tdmowrer** 2020-07-28 17:07 UTC
Labels: bug
