### ISSUE TITLE
 Unity world space canvas button sometimes works/sometimes not

### ISSUE THREAD

**Issue by QasimSajid** [Unity-Technologies/arfoundation-samples#600] opened 2020-09-10 16:01 UTC
Hi, I just started using Unity AR Foundation a few days ago. I was playing with AR Image Tracking today and after the image has been tracked I am enabling a world space canvas with an interactable button and that canvas is following the AR Camera with a "transform.LookAt" function. I am able to press the button from some camera angle but the button becomes un-interactable from most of the other camera angles even when there is nothing between the screen and the button.

**Comment by mdurand42** [comment] 2020-09-10 22:41
This sounds more with an issue with the interactable button more than the image tracking functionality of AR Foundation. Can you perhaps try reproducing in the editor using the same interactable button and see whether it has a similar issue.

**Comment by Qskakar** [comment] 2020-09-11 08:17
Yes, image tracking part is working fine. But I am unable to interact with the button on the world space canvas in the mobile build. I verified it on the editor and it is working fine.

Button is not press-able in the below two screenshots:

![NotWorking1](https://user-images.githubusercontent.com/43292804/92890770-b9643a00-f417-11ea-9891-bad0aee64de1.jpg)

![NotWorking2](https://user-images.githubusercontent.com/43292804/92890776-b9fcd080-f417-11ea-9a78-6f33d2cbda88.jpg)


But in the below screenshot, the button can be pressed:

![Working](https://user-images.githubusercontent.com/43292804/92890974-def14380-f417-11ea-92c2-6aab3019cdc3.jpg)

**Comment by Qskakar** [comment] 2020-09-15 08:37
So I tried to solve the problem again and it has been solved. Actually, I had a transform.LookAt function on the main "ARTrackedImage" object which was being instantiated after an image was tracked. I removed the LookAt function from the main object and added it on the child canvas and doing this resolved the issue. Now the button can be pressed easily from all the angles. Somehow the LookAt function on the "ARTrackedImage" object was causing the issue. Can you think of a reason why it would do that? Or adding a LookAt function on a trackable object is wrong?

**Comment by mdurand42** [comment] 2020-09-15 22:36
We're glad that you found a solution. It's not clear why it was not working before but since the ARTrackedImage is doing its job for you it is appropriate to close the issue.

**Closed by mdurand42** 2020-09-15 22:36 UTC
Labels: how to, needsinvestigation

**Comment by yosun** [comment] 2021-02-04 19:37
Also confirmed world canvas buttons do not work if LookAt camera is assigned
