### ISSUE TITLE
iOS 16 Body Tracking Leg pose not correct & App quit unexpectedly

### ISSUE THREAD

**Issue by Cstedmund** [Unity-Technologies/arfoundation-samples#1032] opened 2022-11-28 06:46 UTC
Hi, I just found out that there have the legs pose is not tracking correctly issue with the body tracking function in ios 16 with the sample project download from here. 
This issue does not exist in ios 15 devices (Tested on iPhone 11 ios 15.7)

The constant crash issue also happened with this log: 
Thread 1: EXC_BAD_ACCESS (code=1, address=0x183af5fe0)
Thread 52: EXC_BAD_ACCESS (code=1, address=0x9078724c0

Does anyone have an idea in solving this issue? Thanks a lot!

===================================== Info =====================================
Project: 2022.1	[5.0 (release)](https://github.com/Unity-Technologies/arfoundation-samples/tree/5.0)
Unity Version: 2021.3.6f1
Google ARCore XR Plugin & Apple ARKit XR Plugin & AR foundation plugin version: 5.0.2
Xcode version: 14.0.1
Device: iPhone SE3 iOS 16.1.1

===================================== Image =====================================
![IMG_7439](https://user-images.githubusercontent.com/92370517/204210747-d1418ecd-5e87-4f9f-a8ed-9fb5343c0e42.PNG)

![IMG_7441](https://user-images.githubusercontent.com/92370517/204210794-376d0c9c-82c1-426e-b587-8f800dda6aa0.PNG)

![IMG_7440](https://user-images.githubusercontent.com/92370517/204210788-6a52ab86-47e5-4f39-98ed-e09152236103.PNG)

[ARSampleLog.txt](https://github.com/Unity-Technologies/arfoundation-samples/files/10101188/ARSampleLog.txt)

**Comment by ankur-unity** [comment] 2022-11-28 07:19
We are aware of this third party issue. The bug is in ARKit Framework on iOS 16+ and cannot be fixed by Unity. We have been able to reproduce this issue in Apple's own sample as well. We have communicated it to Apple already.

I recommend submitting a bug to Apple directly: https://developer.apple.com/bug-reporting/

**Comment by Cstedmund** [comment] 2022-11-28 07:27
> We are aware of this third party issue. The bug is in ARKit Framework on iOS 16+ and cannot be fixed by Unity. We have been able to reproduce this issue in Apple's own sample as well. We have communicated it to Apple already.
> 
> I recommend submitting a bug to Apple directly: https://developer.apple.com/bug-reporting/

Got it and Thanks a lot

**Comment by ankur-unity** [comment] 2022-11-29 20:19
@Cstedmund - Can you provide details on the crash that you're seeing: stacktrace from Xcode log? May be that can shed some light on the origin of the crash. On which iOS device are you seeing the crash?

Is the Unity version you listed in the post accurate? Unity 2021.1.6f1 doesn't support AR Foundation 5.0. It's only supported in 2021.2 and above editor versions.

**Comment by Cstedmund** [comment] 2022-12-08 07:55
Hi @ankur-unity ,
Yes, Sorry for the typo and late reply. I using the Unity Version of 2021.3.6f1 for opening the sample project.
For the Crashing error, sorry that I cannot reproduce that error today. 
But dunno why the error log always happens when I change the device orientation:
2022-12-08 15:51:52.277135+0800 ARFoundationSamples[11039:3230241] [ABPKAlgorithm]  		 Registration Failed)

I have seen the crashing issue happen in iPhone SE3 and iPhone 13 Pro Max.

Thanks for your help,
Edmund

**Comment by digitalmonkey** [comment] 2023-02-05 21:16
Hi @ankur-unity, I ran into these issues as well. I was able to upgrade my iPad Pro to iOS 16.3 and that seems to fix the feet tracking issues for me. I tested this both with my Unity scene as well as the standalone Apple project BodyDetection in CapturingBodyMotionIn3D.

**Comment by Cstedmund** [comment] 2023-02-08 03:20
Hi @digitalmonkey , Thanks for the update. It seems ios 16.3 has remedied the issue.

**Comment by andyb-unity** [comment] 2023-04-13 22:06
Closing this issue as resolved. Looks like Apple fixed this in iOS 16.3. Feel free to re-open the issue if you have further questions.

**Closed by andyb-unity** 2023-04-13 22:06 UTC
Labels: bug, third party
