### ISSUE TITLE
XCode cannot find 'ReferenceImageLibrary' on ARKit

### ISSUE THREAD

**Issue by SushiRoll53** [Unity-Technologies/arfoundation-samples#440] opened 2020-04-02 22:24 UTC
I am working on developing an app on IOS with Unity. I use AR Foundation on Unity and ARKit on IOS, my issue is when I try to use the image targeting, specifically the "ReferenceImageLibrary" which XCode says that it cannot find, even though I double checked and it is there. I get the following error on XCode:

[General] No resource group with name "ReferenceImageLibrary_CF9AB49B-B0D2-4B4E-92A0-743F79544309" found
InvalidOperationException: Failed to set requested image library 'ReferenceImageLibrary' on 
ARKit - there is no matching resource group, or the resource group does not contain any
reference images.

Things I have tried:
- Make the path "Absolute Path" for the ImageLibrary
- Use the ReferenceImageLibrary that has VR googles on it
- Use different logos of appropriate sizes and extensions (.png)
- Export directly from Unity to an xCode app
- Tried different versions of AR Foundation and ARKit
- Using only UnityFramework as my only target membership
- Using both as my target membership

Versions currently using:
- Xcode 11.3.1
- Unity 2019.3.5f1
- AR Foundation 2.1.4
- ARKit 2.1.1

Let me know if more detail is required. Thank you!

**Comment by tdmowrer** [comment] 2020-04-02 22:39
> the "ReferenceImageLibrary" which XCode says that it cannot find, even though I double checked and it is there.

By "it is there" do you mean it is in Unity, or you actually see the asset catalog in Xcode?

If you don't see the catalog in Xcode, it means ARFoundation didn't build it. There is an issue with Unity's asset database where it sometimes "forgets" there are any `XRReferenceImageLibrary`s. Try removing your `Library` folder and try again.

**Comment by SushiRoll53** [comment] 2020-04-02 22:57
Apologies for the abiguity, but yes I see the `XRReferenceImageLibrary` on Xcode
and what `Library` folder is the one that I should remove?

**Comment by tdmowrer** [comment] 2020-04-02 23:01
If you see it in Xcode, then you don't need to remove your `Library` folder (I meant the one in your Unity project).

Okay, does the AR Resource Group named `ReferenceImageLibrary_CF9AB49B-B0D2-4B4E-92A0-743F79544309` actually have images in it? And are any of the images duplicates? (I've seen issues with this before.)

**Comment by SushiRoll53** [comment] 2020-04-03 01:19
Yes, it does have the two images I added, one is .png and the other is .jpg

**Comment by tdmowrer** [comment] 2020-04-03 04:32
Does the png have any transparency? Are there any warnings associated with the images (little orange triangle warning)? I suspect that if ARKit doesn't like the input images it may drop the reference image set.

**Comment by SushiRoll53** [comment] 2020-04-03 05:19
No the .png does not have transparencies & there are no warning signals on the images
I think the issue happens when I build from Unity to IOS, is there a way to do it manually? 
or any other way to build from Unity to IOS?

**Comment by tdmowrer** [comment] 2020-04-03 16:10
Sorry, do what manually?

**Comment by SushiRoll53** [comment] 2020-04-03 16:18
Export the target image manually
or what would be the reason that xcode cannot find the ARReferenceLibrary?

**Comment by tdmowrer** [comment] 2020-04-03 16:33
> Export the target image manually

You can build your own AR Resource Group in Xcode, but the resource group exists already, so that doesn't seem to be the problem.

> what would be the reason that xcode cannot find the ARReferenceLibrary?

I have seen it silently reject resource groups (so they can't be found at runtime) if there are errors or duplicates. Do you have another reference image library with similar images?

If not, please [submit a bug](https://unity3d.com/unity/qa/bug-reporting) with your project and post the bug id here.

**Comment by tdmowrer** [comment] 2020-04-27 16:18
It's been a few weeks since the last response, so I'm closing this issue. If it continues to be a problem, please reopen this issue, submit a bug with a project that reproduces the problem and post the bug id here.

**Closed by tdmowrer** 2020-04-27 16:18 UTC
Labels: more info required

**Comment by machi233** [comment] 2021-04-01 19:11
Hi I have same issue.
In my case it occurs only UAAL project.

**Comment by marchenterprise** [comment] 2021-04-09 09:44
I also got the error "Failed to set requested image library'ReferenceImageLibrary' on ARKit --there is no matching resource group, or the resource group does not contain any reference images." In the UAAL project.

Inevitably I can copy the exported project Unity-iPhone/ARReferenceImages.xcassets separately from the copy of the UnityFramework folder and paste it under MyProjectFolder/ in My Project and Xcode will find it. It is now possible.

**Comment by marchenterprise** [comment] 2021-10-13 22:32
I ended up solving this problem by manually copying and pasting "MyProject --ARReferenceImages.xcassets" under the Xcode project that introduced uaal and referencing it. Good grief.

**Comment by Ahmadre** [comment] 2022-05-15 20:54
> I've tried that again and it worked now. The issue was that I copied the ARReferenceImages.xcassets to the Xcode project that uses UAAL using the macOS Finder. This didn't set the reference to the actual Xcode project.
> 
> To solve the problem I copied ARReferenceImages.xcassets to my Desktop, opened up Xcode and added the folder by right clicking the project file of the project that uses UAAL and selecting "Add files to ". After that, I was able to see the "ARReferenceImages.xcassets" folder in my Xcode project. Make sure to select the correct Target Membership of the folder.

Thank you for your comment! It's very important to export the xcassets to Desktop and reimport via "Add files to"! Thank you so much!

**Comment by marchenterprise** [comment] 2022-05-15 21:02
I'm glad that the problem has improved!
