### ISSUE TITLE
Multiplayer Game not working properly

### ISSUE THREAD

**Issue by miscrealitystudios** [Unity-Technologies/arfoundation-samples#90] opened 2019-01-22 05:13 UTC
Hello Sir,
I created a streetfighter multiplayer game using photon in AR Foundation. I tested the app on both ios and android device. Everything is working properly but the only problem is that the players are not spawning correctly. one player that is spawning is a little above the plane. Here's the video that will give you the exact look of the above problem. Please do watch it!
https://youtu.be/twJAkQYm5tk

**Comment by tdmowrer** [comment] 2019-10-07 00:26
Duplicate of https://github.com/Unity-Technologies/arfoundation-samples/issues/93

**Closed by tdmowrer** 2019-10-07 00:26 UTC
Labels: duplicate
