### ISSUE TITLE
[Bug]Ar foundation Image Tracking Is not working Properly ..!!

### ISSUE THREAD

**Issue by Ahmadhumayoun** [Unity-Technologies/arfoundation-samples#898] opened 2021-10-29 15:56 UTC
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Unity version
 - ARFoundation version

**Comment by tdmowrer** [comment] 2021-10-29 18:10
Duplicate of https://github.com/Unity-Technologies/arfoundation-samples/issues/899

**Closed by tdmowrer** 2021-10-29 18:10 UTC
Labels: bug

**Comment by Ahmadhumayoun** [comment] 2021-10-29 18:21
> Duplicate of #899

Hey @tdmowrer 
Can I have solution of my problem..
Please guide me a little bit...!!
I am really really stucked here..!!
kindly help me out
