### ISSUE TITLE
ARFoundation integrated in ios native app as library crashes with EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by pnok** [Unity-Technologies/arfoundation-samples#337] opened 2019-10-23 10:09 UTC
I built an **AR iOS** project using **ARFoundation 1.5.0**, **ARKit XR plugin 2.2.0**, with **Unity 2018.4.8f1** version and **XCode 11**.

As **standalone** iOS app it works.

Then I tried to **integrate** the Unity XCode project as *library* in an exisisting ios **native** project. The build process succeeded, but as soon as I ran the app on an iphone 7 plus device it crashed with **EXC_BAD_ACCESS**.

The error has been raised by the **unity_init** func in *AppDelegate* class. In details the crash happens at **UnityInitRuntime** inside the unity_init function.

Any suggestions?

Thanks

**Comment by simonevilla** [comment] 2019-10-28 09:44
Hi all,

same issue for me; any solutions?

**Comment by nilsk123** [comment] 2019-10-29 18:22
Same

**Comment by mdurand42** [comment] 2020-06-02 22:48
Do you think it might be a duplicate of this resolved issue? https://github.com/Unity-Technologies/arfoundation-samples/issues/95

**Closed by mdurand42** 2020-06-02 22:48 UTC

**Comment by ROBYER1** [comment] 2023-03-17 12:09
Since nobody else bothered to do it, I have reported this issue being caused by MultiThreaded Rendering at Unity Bug: IN-35599 - [AR Foundation] MultiThreaded Rendering crash AR Foundation when enable/disable AR Session on iOS+Android

Forum post: https://forum.unity.com/threads/multithreaded-rendering-crash-ar-foundation-when-enable-disable-ar-session.1413507/
