### ISSUE TITLE
Position not going to reset once switch scene

### ISSUE THREAD

**Issue by Unity3D-Hardik** [Unity-Technologies/arfoundation-samples#1008] opened 2022-09-27 10:06 UTC
How do I...
Hello, Any one know how we can reset AR Session after switching scene. ? 

Issue : Camera position not going to Vector.zero 

How to reproduce : 
- Create Empty scene with button  Name it Menu
- Create one more scene with AR Session scene (Plane tracking sample from this repository)
- From main menu load Plane Taking scene  Check starting Camera position its around zero , 
- move 1-2 meter and check camera position again and note
- Switch back to Menu 
- again click on button on main to start AR scene 
- Note Camera position (its same as old close AR scene )

Any one know how can i reset AR Scene camera Position ? 

I am using Unity 2021.3.10 and Latest AR Foundation GitHub repository sample

**Comment by Unity3D-Hardik** [comment] 2022-09-27 10:22
Destroy AR Session Game object tested with no luck.

**Comment by ankur-unity** [comment] 2022-09-27 18:29
To reset the session, you can use the `ARSession.Reset()` API which will also reset the camera position to zero. Note that resetting the ARSession will also destroy all the trackables.
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARFoundation.ARSession.html#UnityEngine_XR_ARFoundation_ARSession_Reset

I also tested the samples from `main` for AR Foundation 5.0.2 on 2021.3.10f1 and couldn't reproduce the issue. The camera reset back to zero when switching scene and when pressing "Reset" button from the SimpleAR scene.

How are you checking the camera position?

**Comment by nextechar-hardik** [comment] 2022-10-01 07:02
I have test that. this only work if we pass reference in button and then call reset method. 
but if we try to get AR Session runtime in script and Call that method its not working.

**Comment by andyb-unity** [comment] 2022-10-04 22:37
Please file a bug and post your case number here so our QA team can take a look: https://unity3d.com/unity/qa/bug-reporting

**Comment by nextechar-hardik** [comment] 2022-10-20 13:22
I am using AR Foundation 4.2.6 , and can reproduce with sample code as well. 
Unity version 2021.3.10

**Comment by nextechar-hardik** [comment] 2022-10-31 15:17
Not able to reproduce in AR foundation 5.0.2.

**Comment by ankur-unity** [comment] 2023-01-24 17:16
Closing as resolved since the issue is not reproducible. If it start to occur again then feel free to file a bug with Unity: https://unity3d.com/unity/qa/bug-reporting

**Closed by ankur-unity** 2023-01-24 17:16 UTC
Labels: how to
