### ISSUE TITLE
OcclusionMeshes problem:All the 3D models disappera beyond the depth limit (30 meterts) .

### ISSUE THREAD

**Issue by yuhacrows** [Unity-Technologies/arfoundation-samples#981] opened 2022-06-06 09:42 UTC
//Take a look at the AR Camera GameObject, a child of the ARSessionOrigin. (Or alternatively, Camera.main via scripting) The default Far Clipping Plane value on the Camera component is 20 meters, which you might want to increase. https://docs.unity3d.com/ScriptReference/Camera-farClipPlane.html//

Hi ARF

Thankyou,but it's not work.Acturelly,I have already change this value to 200 before I post this problem.But the red balls still disappera at about 25-30 meters.
I think it's depth map's max value problem.If the distance >20~30meters,the depth image will show a pink color.
If turn off the Temporal Smoothing of the depth map.And rotate phone fast.
It will show 3D model>30meters at once,because the phone has‘t calculate the depeh.And the the depth image show a dark blue color.
After one second,it calculate the depth,depth image turn to pink color.And the 3D model>30meters disappera.

So maybe it'a depth generate problem.If distance >25-30meters,it will give a value set it at 25-30.The max depth value.
I think just don't limit the max value.If distance >25-30meters,set it to a unidentified distance value.Same as the dark blue color in the depth image.This should fix the problem.

Sorry for my bad Enlgish.

**Comment by ankur-unity** [comment] 2022-06-09 23:24
Duplicate of #979. Please re-open the existing issue (#979) instead of opening a new one.

**Closed by ankur-unity** 2022-06-09 23:24 UTC
Labels: how to

**Comment by yuhacrows** [comment] 2022-06-14 05:56
> 

I can't re open that #979

**Comment by yuhacrows** [comment] 2022-06-14 05:56
> Duplicate of #979. Please re-open the existing issue (#979) instead of opening a new one.

I can't re open that https://github.com/Unity-Technologies/arfoundation-samples/issues/979
