### ISSUE TITLE
[bug][reproducible] Shaky camera on android devices when artrackedimagemanager is enabled and match framerate is disabled

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#428] opened 2020-03-12 16:55 UTC
Hi,

I have found a bug in all recent versions of the arcore package (including the latest preview.7)

When the artrackedimagemanager is **enabled** and the match framerate option is **disabled** the camera becomes very shaky/jittery on most (but not all) Android devices.

I have confirmed this behaviour in Unity 2019.2 and 2019.3, and on Android 8, 9 and 10.

Steps to reproduce:

 - Clone samples repository
 - Open ImageTracking scene
 - Disable match framerate option
 - Build and deploy

Video:

https://drive.google.com/file/d/1N8KZzKQ-0tflq7QeNfiFhoIdXkJfKaj0/view?usp=drivesdk

**Comment by tdmowrer** [comment] 2020-03-12 22:59
This sounds like a duplicate of https://github.com/Unity-Technologies/arfoundation-samples/issues/416?email_token=ABFUVCP7BZABGJFM5W5VLLLREZ2NPA5CNFSM4KZIZKC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENAMHIA#issuecomment-591446944

However, the "Match framerate option" is designed specifically to alleviate this problem. Why do you want to disable it?

**Comment by nilsk123** [comment] 2020-03-12 23:04
> This sounds like a duplicate of #416
> 
> However, the "Match framerate option" is designed specifically to alleviate this problem. Why do you want to disable it?

Looking at the issue you referenced the issue we see is much more severe than theirs, did you watch my sample video?

If I understand correctly enabling match framerate limits UI rendering to the camera framerate which makes it look stuttery when animating (correct me if I'm wrong)

**Comment by tdmowrer** [comment] 2020-03-13 01:03
There are two separate but similar issues discussed in #416. The link was supposed to be to a specific comment within issue 416 -- see https://drive.google.com/file/d/1LPXK3nEIZVFBj6W18S2pYaCg0-4q-Jex/edit. It looks like your video.

> If I understand correctly enabling match framerate limits UI rendering to the camera framerate which makes it look stuttery when animating (correct me if I'm wrong)

It limits the Unity framerate to the ArCore framerate. This causes the ARSession update to block until a new ArFrame is received from ArCore. I don't quite grok why that would result in a stuttery animation, though. Could you post a video of that (i.e., the same app but with the match framerate option enabled)?

**Comment by nilsk123** [comment] 2020-03-13 06:58
> There are two separate but similar issues discussed in #416. The link was supposed to be to a specific comment within issue 416 -- see https://drive.google.com/file/d/1LPXK3nEIZVFBj6W18S2pYaCg0-4q-Jex/edit. It looks like your video.
> 
> > If I understand correctly enabling match framerate limits UI rendering to the camera framerate which makes it look stuttery when animating (correct me if I'm wrong)
> 
> It limits the Unity framerate to the ArCore framerate. This causes the ARSession update to block until a new ArFrame is received from ArCore. I don't quite grok why that would result in a stuttery animation, though. Could you post a video of that (i.e., the same app but with the match framerate option enabled)?

You are right, that does look like the same issue. I had seen that thread before but only read the opening post.

So are you saying that this isn't an issue to begin with and expected behaviour, or that it's an issue for which a workaround has already been provided (the match framerate option)?

In that thread you say 

> Matching the frame rate means Unity won't render the next frame until it has a new frame from ARCore to render.

Wouldn't that naturally limit the amount of UI frames Unity draws, and therefore impede smoothness of animations? We tend to set applications target framerate to 60, AR or no AR.

I'm going to try to confirm that enabling the match framerate noticeably affects animations and make a video of it. Thanks for the replies.

**Comment by tdmowrer** [comment] 2020-03-13 17:58
> So are you saying that this isn't an issue to begin with and expected behaviour, or that it's an issue for which a workaround has already been provided (the match framerate option)?

When multithreaded rendering is enabled and the frame rate is not synchronized, I don't believe there is much we can do. The match framerate option is not intended as a workaround for this issue per se, but it is usually a desirable feature that also addresses this problem. 

> Wouldn't that naturally limit the amount of UI frames Unity draws, and therefore impede smoothness of animations?

ArCore steps at 30 Hz on most devices; some can do 60 (see [this chart](https://developers.google.com/ar/discover/supported-devices)), so in many cases it would limit you to 30 fps.

> We tend to set applications target framerate to 60, AR or no AR.

That makes sense, though without any synchronization it means you will very often get the same camera texture a few frames in a row and then skip over one entirely. So the AR experience won't be as smooth.

You might be able to get the best of both worlds by toggling the "Match frame rate" option every other frame and setting the target framerate to 60 fps in a separate MonoBehaviour. That way you are still synchronized, but you end up stepping Unity twice for each 30 Hz ArFrame. Make sure you don't do that if ArCore is already running at 60 Hz, though.

**Comment by nilsk123** [comment] 2020-03-15 21:58
> > So are you saying that this isn't an issue to begin with and expected behaviour, or that it's an issue for which a workaround has already been provided (the match framerate option)?
> 
> When multithreaded rendering is enabled and the frame rate is not synchronized, I don't believe there is much we can do. The match framerate option is not intended as a workaround for this issue per se, but it is usually a desirable feature that also addresses this problem.
> 
> > Wouldn't that naturally limit the amount of UI frames Unity draws, and therefore impede smoothness of animations?
> 
> ArCore steps at 30 Hz on most devices; some can do 60 (see [this chart](https://developers.google.com/ar/discover/supported-devices)), so in many cases it would limit you to 30 fps.
> 
> > We tend to set applications target framerate to 60, AR or no AR.
> 
> That makes sense, though without any synchronization it means you will very often get the same camera texture a few frames in a row and then skip over one entirely. So the AR experience won't be as smooth.
> 
> You might be able to get the best of both worlds by toggling the "Match frame rate" option every other frame and setting the target framerate to 60 fps in a separate MonoBehaviour. That way you are still synchronized, but you end up stepping Unity twice for each 30 Hz ArFrame. Make sure you don't do that if ArCore is already running at 60 Hz, though.

Thanks for the in depth response. Is there any reason this only happens with image tracking enabled?

**Comment by tdmowrer** [comment] 2020-03-20 21:39
> Is there any reason this only happens with image tracking enabled?

I believe it's an implementation detail of ARCore, but I don't know exactly, no.

**Closed** 2020-03-20 21:52 UTC
