### ISSUE TITLE
Session Drift on similar marker.

### ISSUE THREAD

**Issue by nextechar-hardik** [Unity-Technologies/arfoundation-samples#1064] opened 2023-02-22 11:50 UTC
Hello Folks , 
I am using AR Foundation with AR Image tracking and Plane tracking functionality. 
I am using QR code as marker (Dynamic library). When we scan marker (QR code ) I am able to get event like Found and lost. 
after that if I am trying to scan Wrong marker (Same Type of QR but not added on Image Tracking Library ) then AR Session drift to that Marker without any event or error. 

First I was thinking due to Image tracking is enable so I have disable Tracking and all its component using this code 

`
   void StopAllTrackable()
        {
            foreach (var trackedImage in m_TrackedImageManager.trackables)
               {
                     LogHandler.Instance.Log("Markers  : " + trackedImage.referenceImage.name);
                     trackedImage.gameObject.SetActive(false);
               }

            m_TrackedImageManager.referenceLibrary = m_TrackedImageManager.CreateRuntimeLibrary();
            m_TrackedImageManager.requestedMaxNumberOfMovingImages = 0;
            m_TrackedImageManager.enabled = false;
        }
`
Still I am facing same issue. 

I am attaching issue video here 

https://youtube.com/shorts/62ixko96bI8

In video i am Tracking first marker , then loading content. then after trying to scan another marker. i can see content on place. 

First both marker are added in Dynamic Library. last one is same way generated QR but not added in Library. at that time Session shift at that marker i can see rest of content is also move accordingly 

Any suggestion for this kind of issue ?

**Comment by nextechar-hardik** [comment] 2023-02-22 11:57
I have test this flow on AR foundation version - 4.2.7 , 5.0.2 , 5.0.3

**Comment by andyb-unity** [comment] 2023-02-23 23:48
I'm not sure exactly what the issue is here, but I have some ideas.

First of all, setting `requestedMaxNumberOfMovingImages` to 0 will result in a tracking configuration change in ARKit as explained here: https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2968182-maximumnumberoftrackedimages?language=objc

> The default value is 0, which disables image tracking. If you add reference images to [detectionImages](https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2941063-detectionimages?language=objc) with this property set to 0, ARKit creates image anchors for observed reference images but their positions only update infrequently, such as once every couple of seconds.

This configuration change could be responsible for your issue, and I would recommend testing with this line commented out.

Another note is that QR Codes are poor images for ARKit image tracking. You might want to consider viewing your image quality in Xcode to confirm whether the image is suitable for tracking, as explained here: https://developer.apple.com/forums/thread/685469

> Not all images are equally suited for using them as ARReferenceImages. Good reference images typically have high contrast, good texture, clear edges, and are printed on a flat, non-glossy surface. Low-texture and low-contrast images will likely not work so well. When you add reference images to an ARResourceGroup in an Xcode asset catalog, Xcode will show quality estimation warnings, which may provide additional insights about the specific issue with that particular image.

**Comment by nextechar-hardik** [comment] 2023-02-24 05:51
@andyb-unity Thank you for replay..
this issue not face on only iOS its also reproducible in Android. 

Sure will try to update code as per your suggestion and test flow. Tracking is also good With QR only..very fast.

I thought issue accrue due to Plane tracking.. while finding marker Plane Tracking is also enable at that time plane is created on Marker as well , so if we scan similar look image at that time due to plane tracking similar environment found AR Foundation reset session anchor... 

May be I am wrong on this theory.. I got this theory because AR Session has capability to improve session pose automatically.
SO want to know is there any way to stop that kind of behaviour ? can we stop auto improvement in session pose ?

**Comment by andyb-unity** [comment] 2023-06-22 22:55
> SO want to know is there any way to stop that kind of behaviour ? can we stop auto improvement in session pose ?

In short, no. The definition of an AR Session being enabled is that it tracks the device's position in the environment to the best of its ability. How it does so is platform-specific, but no platform offers anything like you describe.

**Comment by andyb-unity** [comment] 2023-09-28 19:55
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.

**Closed by andyb-unity** 2023-09-28 19:55 UTC
Labels: how to
