### ISSUE TITLE
Tracking issues on iPhone 11 pro max

### ISSUE THREAD

**Issue by DiveshNaidoo** [Unity-Technologies/arfoundation-samples#349] opened 2019-11-02 20:37 UTC
Hi, today I switched devices from a Huawei Mate 20 Pro to the iPhone 11 Pro Max and I’m having serious tracking issues. I am using the latest stable Unity release and all the latest preview packages (ARkit, ARfoundation) as well as LWRP. The tracking on the Huawei is great but on the iPhone it takes a good 20 seconds before it begins the initial track and thereafter, the tracking is very unstable, debug points consistently drift around and there are only brief moments where the tracking stabilizes. I am using the samples to test.

**Comment by DiveshNaidoo** [comment] 2019-11-03 06:35
It seems that this may be an iOS 13 issue.

**Comment by tdmowrer** [comment] 2019-11-05 18:42
I tested the SimpleAR sample on an iPhone 11 Pro. The detection behavior is a bit different from previous devices, but the tracking is stable. For example, several seconds pass without any feature points or planes, and then 100+ feature points and a large plane will suddenly appear. The iPhone 11 "pro" models use a wide angle lens for AR, so there will probably be subtle differences in the detection behavior.

However, I am not able to reproduce the unstable tracking you mentioned.

> It seems that this may be an iOS 13 issue.

Are you on a beta or non-beta version of iOS 13?

**Comment by fayezsalka** [comment] 2019-11-06 10:52
I noticed degraded tracking accuracy with the new iPhone 11 Pro Max, the iPad Pro has a much better accuracy even though it's an older device (A12X chip vs A13). You can verify it by adding a 3d object on top of a real landmark then moving around the landmark, on iPhone 11 there will be considerable tracking drift (5 to 10 cm) after moving around the object that is enough to break the experience especially if you are trying to overlay virtual object on top of real objects (if you are just adding objects to a horizontal plane the tracking drift might be unnoticeable)

**Comment by fayezsalka** [comment] 2019-11-06 10:54
It could be an issue with wrong factory/iOS 13 calibrations of the new iPhone lenses.

**Comment by DiveshNaidoo** [comment] 2019-11-06 11:05
I tested on an iPhone X and the tracking overall in different environments is definitely more stable on the X vs the Pro Max.

Also one other thing that I am trying to figure out and this is most likely an iOS issue affecting all devices without the home button. When I disable the on screen home bar in the Unity player settings, for some reason the quality of screen recording on the device drops drastically. I am trying to take a screen recording without the grey home bar visible. Is there any known way around this?

**Comment by smtabatabaie** [comment] 2020-01-11 15:17
Hi guys, I'm testing on my iPhone XS max and I have 1 meter drift in every 10 meter movement from my initial location. I wanted to ask if the drift issue is less in iPhone 11 or not, and if it is, how much it has improved?
Thanks

**Comment by tdmowrer** [comment] 2020-07-02 23:05
HI folks -- this seems to be an older discussion on the differences in iOS hardware, and I don't think there's anything actionable by Unity. I'm going to close it for now, but please reopen it if you have more questions or information.

**Closed by tdmowrer** 2020-07-02 23:05 UTC
Labels: cannot reproduce
