### ISSUE TITLE
[bug][reproducible]Session can't be destroyed or re-enabled on Android after querying availability

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#414] opened 2020-02-21 09:17 UTC
Hello,

We have further debugged and found the root cause of these two bugs I logged previously:

https://github.com/Unity-Technologies/arfoundation-samples/issues/411
https://github.com/Unity-Technologies/arfoundation-samples/issues/412

There is a bug in the arcore package which crashes the device if you have queried arsession availability and then try to either destroy the session or enable it _twice_

This regression was introduced in arcore xr plugin 3.1.0-preview.4, preview.2 works fine

This is perfectly reproducible across Android and Unity versions, we have attached a minimal reproduction case:

 - Start samplescene
 - Click one of the buttons to either query availability and destroy the session or query availibity and enable the session twice
 - Observe crash
    

[Ar Foundation Ar Session Bug.zip](https://github.com/Unity-Technologies/arfoundation-samples/files/4235227/Ar.Foundation.Ar.Session.Bug.zip)
[EnableSessionTwice.log](https://github.com/Unity-Technologies/arfoundation-samples/files/4235229/EnableSessionTwice.log)
[DestroySession.log](https://github.com/Unity-Technologies/arfoundation-samples/files/4235230/DestroySession.log)

**Comment by DavidMohrhardt** [comment] 2020-02-21 17:12
Thanks for bisecting this issue.  I am still looking into the cause but this is a huge help!

**Comment by DavidMohrhardt** [comment] 2020-02-24 19:49
We have a fix out that will be in the next release.  I can't say when that will be exactly but it should be fixed in the next preview version.

**Closed** 2020-03-12 07:26 UTC
Labels: bug
