### ISSUE TITLE
ARFoundation not working on split Android App Bundle

### ISSUE THREAD

**Issue by msNEOANALOG** [Unity-Technologies/arfoundation-samples#941] opened 2022-02-18 08:56 UTC
Hey all, 
when we try to test our AR App using **AR Foundation** on Android via the Google Play Console it just does not work. The AR Content does not move relative to the camera. The app is bigger then 150MB so we have Player Settings>Publishing Settings>**Split Application Binary** = on. And we have to build as Android App Bundle for the Play Store. It works perfectly without splitting build&run on device. 
We saw this [article](https://github.com/Unity-Technologies/arfoundation-samples/issues/96) where **splitting by architecture** seems to solve the problem. But since Google updated the rules, we have to upload an **AAB**. Not several APKs. 
 We're stuck. Any ideas? Thanks!

**Comment by ankur-unity** [comment] 2022-02-18 22:55
**Split Application Binary** does not split an Android app into APK and AAB (asset bundle). It creates APK and OBB files. To create an AAB file, use "Build App Bundle (Google Play)" option in the **Build Settings > Android**.

**Comment by msNEOANALOG** [comment] 2022-02-19 09:24
> **Split Application Binary** does not split an Android app into APK and AAB (asset bundle). It creates APK and OBB files. To create an AAB file, use "Build App Bundle (Google Play)" option in the **Build Settings > Android**. https://docs.unity3d.com/Manual/android-BuildProcess.html

Thanks ankur-unity. We are doing that. The problem is that ARFoundation does not work when the AAB is installed via Play Console. It shows no errors and initializes normally but the rotation and position of the camera is fixed.

**Comment by ankur-unity** [comment] 2022-02-25 02:35
> Thanks ankur-unity. We are doing that. The problem is that ARFoundation does not work when the AAB is installed via Play Console. It shows no errors and initializes normally but the rotation and position of the camera is fixed.

You mentioned in your original post that:
> we have Player Settings>Publishing Settings>Split Application Binary = on

This will create an OBB file. You will need to turn that off to avoid this. You only need to check the option "**Build Settings > Android > Build App Bundle (Google Play)**" to create an AAB file.

**Comment by msNEOANALOG** [comment] 2022-02-25 09:00
Dear ankur-unity. Thanks for the reply. The thing is, that we have to split the AAB because it is bigger than 150MB and Google Play Console will not accept that. As soon as we split it, AR Foundation stops working properly.

We were not able to figure that out and are now moving to external addressables to make the app smaller and deploy it without splitting.

**Comment by eisenWu** [comment] 2022-02-25 17:02
Hi I think I have same issue as yours. When build the apk from unity, it works fine, but once I build the aab file and upload to google play console, it will generate a apk file, but the apk does not work, when the ar session active is, the app crashed...

**Comment by eisenWu** [comment] 2022-02-25 17:05
PLS let me know if you find any resolution for that... I will try my best to solve it, if I figur it out, I will come here to you same.

**Comment by msNEOANALOG** [comment] 2022-02-25 17:14
> Hi I think I have same issue as yours. When build the apk from unity, it works fine, but once I build the aab file and upload to google play console, it will generate a apk file, but the apk does not work, when the ar session active is, the app crashed...

We do not have problems with AABs per se. Only when they are split. No matter if we build&run a split AAB directly to device or via Play Console.

**Comment by eisenWu** [comment] 2022-02-25 17:18
> > Hi I think I have same issue as yours. When build the apk from unity, it works fine, but once I build the aab file and upload to google play console, it will generate a apk file, but the apk does not work, when the ar session active is, the app crashed...
> 
> We do not have problems with AABs per se. Only when they are split. No matter if we build&run a split AAB directly to device or via Play Console.

ok... you app works fine when they are not split? my issue happens when I turn on the ar session... using the unity 2021.2.13 and ar foundation 4.2.2

**Comment by msNEOANALOG** [comment] 2022-02-25 17:19
> you app works fine when they are not split?

Yes.

**Comment by eisenWu** [comment] 2022-02-25 17:27
> > you app works fine when they are not split?
> 
> Yes.

how do you know that... you can not upload the aab file bigger than 150 MB and that is the reason why you split it. I mean my app works fine when it not uploaded.

**Comment by msNEOANALOG** [comment] 2022-02-25 17:33
> how do you know that... you can not upload the aab file bigger than 150 MB and that is the reason why you split it. I mean my app works fine when it not uploaded.

I tried it with the ARFroundation example from Unity. It is split, but small. Didn't work. The scene is fixed to the camera.

**Comment by eisenWu** [comment] 2022-02-25 17:37
> > how do you know that... you can not upload the aab file bigger than 150 MB and that is the reason why you split it. I mean my app works fine when it not uploaded.
> 
> I tried it with the ARFroundation example from Unity. It is split, but small. Didn't work. The scene is fixed to the camera.

So you mean the ar-foundation exsample aab file can be uploaded, and the apk from google play console works even the ar-foundation exsample was not splited

**Comment by eisenWu** [comment] 2022-02-25 17:48
because I even tried with blank scene, only ar session and ar session origin, it crashed same...

**Comment by msNEOANALOG** [comment] 2022-02-25 19:23
> So you mean the ar-foundation exsample aab file can be uploaded, and the apk from google play console works even the ar-foundation exsample was not splited

It works as long as it is not splitted. Wether it's an APK or an AAB.

**Comment by pacolaf** [comment] 2022-03-15 19:36
> This is a known issue. As noted in this thread, the issue only occurs when the app is compiled with "Split Binary" option. The issue occurs because the `UnitySubsystemsManifest.json` file that's required for AR Input Subsystem always exist in the main APK while it's being searched in the obb at runtime, if the app was compiled with split binary mode.
> 
> The progress on a fix can be tracked here: https://issuetracker.unity3d.com/issues/android-xr-tracking-is-not-working-when-building-app-bundle-with-split-application-binary-enabled

Thanks for the information! I just installed version 2021.2.4f1 and it works. I will keep on using this version until the issue is fixed.

**Comment by pacolaf** [comment] 2022-05-10 10:53
This issue is finally fixed in 2021.3.2f1. I have tested it and it works fine.

**Closed** 2022-05-10 16:10 UTC
Labels: bug, fixed
