### ISSUE TITLE
Build Error with il2cpp

### ISSUE THREAD

**Issue by JustKoTMurchik** [Unity-Technologies/arfoundation-samples#255] opened 2019-08-06 19:05 UTC
I just download arfoundation-samples, then I change scripting backend to il2cpp and get this error.
http://prntscr.com/op7p60
http://prntscr.com/op7pcu
http://prntscr.com/op7pht
http://prntscr.com/op7re9
Can I build for ARM64 with il2cpp?
My current ver unity is 2019.2.0f1. But I get this error with 2019.1.12

**Comment by areavisuale** [comment] 2019-08-07 07:34
Do you have link.xml in your assets folder?

**Comment by JustKoTMurchik** [comment] 2019-08-07 08:55
Hi, i think no.
Can you send screenshot how it look like?

P.S. I just fix this issue. 

I have other arfoundation sample.zip which i downloaded before. 
And I can build that source code with il2cpp for ARM64.

**Comment by areavisuale** [comment] 2019-08-07 08:58
I read somewhere that you need link.xml in yor assets folder to avoid that some files are removed using IL2CPP. This is the link.xml:

`<linker>
    <assembly fullname="Unity.XR.ARCore" ignoreIfMissing="1" preserve="all"/>
    <assembly fullname="Unity.XR.ARKit" ignoreIfMissing="1" preserve="all"/>
</linker>`

**Comment by JustKoTMurchik** [comment] 2019-08-07 09:08
Ok, thank you.

**Comment by tdmowrer** [comment] 2019-10-06 07:30
This sounds like a duplicate of https://github.com/Unity-Technologies/arfoundation-samples/issues/292 which was just an issue with the samples. Should be fixed now.

> I read somewhere that you need link.xml in yor assets folder to avoid that some files are removed using IL2CPP. This is the link.xml:
> 
> ```
> <linker>
>     <assembly fullname="Unity.XR.ARCore" ignoreIfMissing="1" preserve="all"/>
>     <assembly fullname="Unity.XR.ARKit" ignoreIfMissing="1" preserve="all"/>
> </linker>
> ```

This is no longer necessary since 2.0

**Closed by tdmowrer** 2019-10-06 07:30 UTC
