### ISSUE TITLE
[Bug] Can't build for Android with ARFoundation and Legacy render pipeline

### ISSUE THREAD

**Issue by kjyv** [Unity-Technologies/arfoundation-samples#557] opened 2020-07-23 10:48 UTC
**Describe the bug**
With the latest ARFoundation and down to at least 4.0.0-preview.3 we can't build for Android without modifying the package content. Building for iOS works fine but when switching to Android, these error show:

```
Shader error in 'Unlit/ARKitBackground': failed to open source file: 'Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl' at line 44 (on gles3)

Compiling Vertex program with ARKIT_BACKGROUND_URP

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_MOBILE UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_RGBM_ENCODING

Shader error in 'Unlit/ARKitBackground': failed to open source file: 'Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl' at line 45 (on gles3)

Compiling Vertex program with ARKIT_BACKGROUND_URP

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_MOBILE UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_RGBM_ENCODING

Shader error in 'Unlit/ARKitBackground': failed to open source file: 'Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl' at line 55 (on gles3)

Compiling Vertex program with ARKIT_BACKGROUND_LWRP

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_MOBILE UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_RGBM_ENCODING

Shader error in 'Unlit/ARKitBackground': failed to open source file: 'Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl' at line 56 (on gles3)

Compiling Vertex program with ARKIT_BACKGROUND_LWRP

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_LIGHTMAP_RGBM_ENCODING
```
This seems to be happening because the shader has a multi_compile_local line with ARKIT_BACKGROUND_URP that in turn tries to import files from the URP package that we don't have installed. The current solution is to manually modify the shader to remove those includes that won't be used anyway. It is weird that it doesn't happen in iOS builds because it looks like this would always fail.

**Smartphone (please complete the following information):**
 - Unity version 2019.4.4f
 - ARFoundation 4.0.0-preview.3 up to 4.1.0-preview.5

**Comment by tdmowrer** [comment] 2020-07-23 15:56
ARFoundation works with both legacy and Universal render pipelines. This sounds like you built for iOS, but at some point the build failed, then switched to Android. When an iOS build fails, build assets (like the shader, specifically) are left in the Player Settings' preloaded assets, which can interfere with future builds for different platforms.

You just need to remove the ARKit shader from Edit > ProjectSettings > Player > OtherSettings > Optimization > PreloadedAssets:

![Screen Shot 2020-07-23 at 8 55 05 AM](https://user-images.githubusercontent.com/4934281/88308794-529d8c80-ccc2-11ea-9b78-594ad449c223.png)

**Comment by kjyv** [comment] 2020-07-23 19:28
Oh well, that seems to be the reason, thanks. I guess it would be nice if the non-matching shaders are removed when also the right one is added automatically.

**Comment by tdmowrer** [comment] 2020-07-23 20:03
I know what you mean, but it is hard for the ARCore package to reason about what should or should not be in the preloaded assets list. We've chatted internally about how we can improve this.

> why are there tabs for Android and iOS in the Project Settings but they both have the same list of preloaded assets?

Yeah, that's a good point; I'm not entirely sure myself.

**Comment by kjyv** [comment] 2020-07-23 21:42
I understand this can be tricky. But as this results in a build error (hence I'm not sure this ticket should already be closed), maybe as a start add a simple error/warning that upon build tells the user that there should not be an ARKit shader in the preloaded assets?

**Comment by tdmowrer** [comment] 2020-07-23 22:08
ARCore is an independent package; it doesn't know about ARKit. And it doesn't know what should or should not be in the preloaded assets already. I do think we can make it better, but it will require some discussions on our side.

**Comment by kjyv** [comment] 2020-07-24 15:14
Well, you know your internal policies. Just another observation: the shader is added on every successful build too, it is not left over from a failed build.

**Comment by tdmowrer** [comment] 2020-07-24 18:13
> the shader is added on every successful build too, it is not left over from a failed build.

That _is_ a bug. It looks like it is caused by the presence of the Input System package -- are you using that package? The Input System also manipulates the preloaded assets and overwrites ARKit's changes in order to restore the list to its "original" state.

**Comment by kjyv** [comment] 2020-07-26 10:26
We are using the new input system, yes.

**Comment by tdmowrer** [comment] 2020-07-28 17:10
This has been fixed in the `4.1.0-preview.6` packages (now available).

I also added a more general fix for "cleaning" the Preloaded Assets array (even for the build failure case I first mentioned). Hopefully, this shouldn't be an issue anymore. The fixes will also be backported to 3.1 verified (the earliest version where this could potentially happen).

**Comment by kjyv** [comment] 2020-07-29 09:50
Yes, I can confirm building works again. Thanks

**Closed** 2020-07-29 23:00 UTC
Labels: bug, fixed

**Comment by derwaldgeist** [comment] 2020-08-12 11:08
Facing the same problem here. When will the fix be backported to ARFoundation 4.0.0? I can't update to 4.1 due to another problem (Face detection descriptors are not recognized anymore).

**Comment by tdmowrer** [comment] 2020-08-12 15:16
It's in the queue. However, you can workaround the issue manually using the technique I described in https://github.com/Unity-Technologies/arfoundation-samples/issues/557#issuecomment-663088194

**Comment by derwaldgeist** [comment] 2020-08-12 17:33
@tdmowrer Yes, I saw that. It worked. What I was wondering: When I removed the ARKit shader and rebuilt the project on iOS later, I suddenly saw the ARCore (!) shader there. Which totally suprised me, as it did not show up in the Android build environment. I have two separate git repo copies, so I just switch repos, not build targets, to switch between platforms.

**Comment by tdmowrer** [comment] 2020-08-12 18:58
The Preloaded Assets are saved in your `ProjectSettings.asset`, so switching branches will set the preloaded assets to whatever is on that branch.

**Comment by tdmowrer** [comment] 2020-09-04 04:31
> Facing the same problem here. When will the fix be backported to ARFoundation 4.0.0? I can't update to 4.1 due to another problem (Face detection descriptors are not recognized anymore).

This fix was included in the recently published 4.0.8 verified packages.

**Comment by josefgrunig** [comment] 2020-12-23 11:32
What are the consequences of removing all preloaded assets from the settings? I cannot upgrade to 4.0.8 right now and everything seems to work correctly once I removed all shaders from preloaded assets. Any issue that can arise?

**Comment by tdmowrer** [comment] 2021-01-04 22:33
> What are the consequences of removing all preloaded assets from the settings?

It is safe to remove anything added by ARFoundation (they will be added back during Player build). I can't speak to other assets that may be in that list.

**Comment by saurabhburadkar** [comment] 2022-11-11 09:21
The preloadedAssets issue is still there, how to resolve this, any suggestions guys?
I am facing an issue in AR. AR camera not working because of this.
