### ISSUE TITLE
Add object to the reference object library at runtime

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/arfoundation-samples#662] opened 2020-11-11 18:46 UTC
I know that it is possible to add adding new reference images at runtime. What about adding object to the reference object library at runtime?

**Comment by tdmowrer** [comment] 2020-11-11 19:00
Duplicate of https://github.com/Unity-Technologies/arfoundation-samples/issues/535

**Closed by tdmowrer** 2020-11-11 19:00 UTC
Labels: duplicate, how to
