### ISSUE TITLE
About scaling content and how to reset the plane

### ISSUE THREAD

**Issue by Leiong** [Unity-Technologies/arfoundation-samples#16] opened 2018-07-11 10:22 UTC
Hi Unity,
Question 1: I want to scale the content rendered by ARSessionOrigin, arsessionOrigin.transform.localScale = Vector3.one * scaleValue, but it will affect the point cloud particle effects. It looks strange, is it something I missed?

Problem 2: Disable ARsession, then enable ARSession, the previous plane still appears and cannot be cleared. I need to implement enable AR, reset AR, close AR, how do I need to set it up;
![aaaa](https://user-images.githubusercontent.com/41097890/42565879-4acb56c4-8537-11e8-982d-88ac4c0ba927.png)
Thanks！

**Comment by timm-unity** [comment] 2018-07-17 05:30
Hi Leiong,

> Question 1: I want to scale the content rendered by ARSessionOrigin, arsessionOrigin.transform.localScale = Vector3.one * scaleValue, but it will affect the point cloud particle effects. It looks strange, is it something I missed?

Could you post a screen shot of the "strange" result?

> Problem 2: Disable ARsession, then enable ARSession, the previous plane still appears and cannot be cleared. I need to implement enable AR, reset AR, close AR, how do I need to set it up;

Thanks for the code snippet. You should not set `ARSubsystemManager.systemState` yourself (the setter should be private -- it's a mistake that it isn't). The correct way to reset the session is to `Destroy` it and re-add it, though there are some known issues with this, particularly on ARKit. This will be fixed in the next preview release. I'm also going to add a method `Reset` to the `ARSession` to make this easier.

**Comment by Leiong** [comment] 2018-07-17 07:40
Hi Timm,
Question 1: When I want to scale the content rendered by ARSessionOrigin, the position of the particle effect is wrong, and the size of the border changes. This is not the result I want.
![img_0033](https://user-images.githubusercontent.com/41097890/42802831-a1e3fe36-89d6-11e8-80af-35dccd806e4a.png)
![img_0034](https://user-images.githubusercontent.com/41097890/42802832-a34f8f74-89d6-11e8-8912-24940040f91c.png)
Question 2:After the Cube is generated, is there a way to remove the particle effects and planes? This will not affect my observation of the object.
（Sorry, this is the text of Google Translate, I hope you can understand it......）

**Comment by timm-unity** [comment] 2018-07-18 21:44
> Question 1: When I want to scale the content rendered by ARSessionOrigin, the position of the particle effect is wrong, and the size of the border changes. This is not the result I want.

Does your point cloud prefab have a non-zero position? It looks like an extra offset is being applied. The line renderer being affected by scale is currently expected. The outline is mostly for debugging purposes. You can simply remove the line renderer from your prefab if you don't want it.

> Question 2:After the Cube is generated, is there a way to remove the particle effects and planes? This will not affect my observation of the object.

Yes. To disable plane detection and point cloud updates, you can disable their managers: `ARPlaneManager` and `ARPointCloudManager`, respectively. To remove existing planes/point cloud from the scene, you can disable or remove their `GameObject`s. You can get all the planes with [`ARPlaneManager.GetAllPlanes`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARPlaneManager.html#UnityEngine_XR_ARFoundation_ARPlaneManager_GetAllPlanes_List_UnityEngine_XR_ARFoundation_ARPlane__) and the point cloud with [`ARPointCloudManager.pointCloud`](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/api/UnityEngine.XR.ARFoundation.ARPointCloudManager.html#properties)

**Comment by southrop** [comment] 2018-07-23 04:30
Hi Tim,

I'm having an issue with point clouds and scaling too. I'm not entirely sure if it's the same as the issue Leiong is having, but it seems related. I'm using a scale of `(300,300,300)` on my `ARSessionOrigin` (due to my models being huge) and the point cloud simply doesn't appear because it is too small. Increasing the particle size in the prefab causes them to reappear but the position(s) are completely wrong.

Without scaling (built from `arfoundation-samples`:
![screenshot_20180723-131424](https://user-images.githubusercontent.com/2568167/43057174-8c500e26-8e7b-11e8-8d64-aaa6aa7a777b.jpg)

With `(300,300,300)` scaling:
![screenshot_20180723-131444](https://user-images.githubusercontent.com/2568167/43057178-909c2370-8e7b-11e8-98b4-f8899c9b11c3.jpg)

The only things changed in my project are the scale and the UI component at the top right.

As you can see from the smaller size of the keyboard in the 2nd screenshot, I've had to move back from my position in the first screenshot in order to actually see the points, meaning the position of the points is completely different. I think what I'm seeing here is all the points clumped together due to the positions being scaled down so their positions no longer visually match with the features detected in the camera.

I read that a remoting method is in the works to allow debugging in the editor, but until that's ready, is there any other way I can try to debug this issue?

**Comment by southrop** [comment] 2018-07-23 07:14
I was having a similar issue to this and scaling the point cloud prefab by the same scale as the `ARSessionOrigin` resolved the issue for me. The points don't appear as nicely as they did before (the bottom half of some of them appear to get clipped off), but at least they're at the right positions.

**Comment by timm-unity** [comment] 2018-07-23 15:38
> I was having a similar issue to this and scaling the point cloud prefab by the same scale as the ARSessionOrigin resolved the issue for me.
That sounds odd. What does your scene hierarchy look like? Does your point cloud prefab have an identity transform?

**Comment by southrop** [comment] 2018-07-24 03:34
> That sounds odd. What does your scene hierarchy look like? Does your point cloud prefab have an identity transform?

My scene hierarchy looks like this. Aside from a few UI-related addition and a camera clipping plane tweak (to account for the 300 scale), it's identical to the sample.

![image](https://user-images.githubusercontent.com/2568167/43115185-b633a1ea-8f3d-11e8-84eb-ce7770363774.png)

I use the default point cloud prefab generated from the Right-Click menu entry, and it has a completely zero'd out transform with the exception of scale.

**Comment by timm-unity** [comment] 2018-07-25 17:17
@Leiong 
Thanks for the screenshots! Very helpful.

> But the planes/point cloud did not appear when ARSession.Reset();

Did you also re-enable the point cloud and plane managers? It looks like you disable them, then reset the `ARSession`, but don't re-enable them. If those managers are disabled, then plane detection and point cloud updates are disabled.

> the point cloud prefab have a non-zero position, but this problem will still appear

The image you posted is of the plane prefab. Can you double check the point cloud prefab?

> Is the method like this?

That is the correct way to scale the `ARSessionOrigin`, yes.

**Comment by timm-unity** [comment] 2018-07-25 17:20
@southrop Hmm. Could you share your project? Either here or send it to me at timm@unity3d.com

**Comment by southrop** [comment] 2018-07-26 04:07
@timm-unity I've sent you an email with a replication

**Comment by timm-unity** [comment] 2018-07-26 06:22
@southrop Thanks; was able to repro, and I know what the issue is. This should solve @Leiong 's problem too.

In your point cloud prefab, change the "Scaling Mode" to "Hierarchy":
![scalemodehierarchy](https://user-images.githubusercontent.com/25465758/43244853-21f1f944-9061-11e8-8b50-0168021243e8.png)

This is what I use to test, but for some reason the point cloud created from the XR menu produces one with Scaling Mode set to "Local". I'll fix the generation util to use the correct setting.

**Comment by southrop** [comment] 2018-07-26 06:57
@timm-unity Brilliant, that resolves it!

While you're making changes to the generation util, perhaps it's worth mentioning that the default point cloud gameobject gets created with the name `AR Default Point Cloud ` with a space at the end. Not really a big issue but seems unintentional.

**Comment by timm-unity** [comment] 2018-07-26 06:59
Nice catch; will do!

**Comment by sergiosolorzano** [comment] 2018-08-03 10:39
Hi all,

I've been pulling hairs to get the object to rotate or scale correctly so I'm back to the well hoping for some help :)

I am using the ARFoundation scene and
ARSessionOrigin m_ARSessionOrigin=GameObject.FindWithTag("ARSessionOrigin").GetComponent<ARSessionOrigin>();
m_ARSessionOrigin.transform.rotation = Quaternion.AngleAxis(rotationSlider.value, Vector3.up); //to rotate
m_ARSessionOrigin.transform.localScale = Vector3.one*scaleSlider.value; // to scale

When scaling I can see on console the scale slider value change, the localScale transform of ARSessionOrigin change, and the object (cube) in the scene transform.position/localScale does not change as expected. However the cube moves as if transposed. The equivalent happens with rotation. 

It also seems the planes are being scaled, can that be avoided or would it make sense using a second camera?

Here's a short video with the cube's behaviour https://youtu.be/BExWpS2y-zU

Can you please share a lead what I'm doing wrong to scale/rotate?

Thanks a bunch for your help! 
Sergio

**Closed** 2019-10-06 23:56 UTC
