### ISSUE TITLE
[Bug] Autofocus stops working on Android after ARSession.Reset()

### ISSUE THREAD

**Issue by Greken80** [Unity-Technologies/arfoundation-samples#1035] opened 2022-12-01 09:47 UTC
Autofocus stops working after i have used Reset in SimpleAR scene.
Seen the same issue in my projects after i use ARSession.Reset() and only experienced the issue on Android devices

1. Build ARFoundation samples for Android
2. Run Simple AR scene
3. Press Reset button

After reset is complete the camera feed is blurry and unfocused. 
If Paus is pressed then Resume the autofocus starts working.

<p float="center">
<img width="322"  src="https://user-images.githubusercontent.com/11785278/205017288-50b75f7a-77b2-4946-8459-7e55c36676ba.jpg">
<img width="322"  src="https://user-images.githubusercontent.com/11785278/205019312-64559ce5-ecf2-44aa-81e4-e9b78c9f53b2.jpg" align="right">
</p>

 - Samsung S21 Ultra 5G
 - Android 13
 - Unity versions 2021.3.7, 2022.2.08b, 2023.1.0a21
 - ARFoundation version  4.2.6, 5.0.3, 5.1.0-pre.2

**Comment by nextechar-hardik** [comment] 2023-02-20 07:53
I have also face this issue , but you can manually set Autofocus property once reset done that will resolve issue. 

FindObjectOfType<ARCameraManager>().autoFocusRequested = true;

**Comment by andyb-unity** [comment] 2023-04-13 22:08
Hi all, thanks for the report. We have fixed this issue internally and will update this thread when we have version numbers for when the fix will land.

**Comment by shb3014** [comment] 2023-04-23 12:23
Same here, setting autoFocusRequested=true does not help.

**Comment by Skaiji** [comment] 2023-04-24 05:50
> Same here, setting autoFocusRequested=true does not help.

Hello! I see we are in the same boat :D

I'm trying to find a solution, if suddenly you manage to solve this problem, could you share the result? I will do the same if I can

Do you have telegram or something like that

**Comment by Skaiji** [comment] 2023-04-24 17:07
> Hi all, you are unable to fix this issue on your end. As a temporary workaround you could consider de-initializing and re-initializing the XR Loader in your project instead of calling ARSession.Reset: https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/SceneUtility.cs
> 
> but this is not a recommended solution long-term. We will have a patch out in about two weeks with a fix for this.

Yes! That helped!
Thanks a lot.

But it seems that the image recognition time has increased, as if 3 times longer than it was before this script

**Comment by Finnalli** [comment] 2023-05-11 12:04
> Hi all, you are unable to fix this issue on your end. As a temporary workaround you could consider de-initializing and re-initializing the XR Loader in your project instead of calling ARSession.Reset: https://github.com/Unity-Technologies/arfoundation-samples/blob/main/Assets/Scripts/Runtime/SceneUtility.cs
> 
> but this is not a recommended solution long-term. We will have a patch out in about two weeks with a fix for this.

Hi, any update on this?

**Comment by andyb-unity** [comment] 2023-05-12 15:40
The fix is merged in on our side. We're kicking off a release soon and will post here when it's live. Release process takes a couple days to get through verification

**Comment by andyb-unity** [comment] 2023-05-22 21:35
Thanks for everyone's patience during our release process.

This issue has been resolved in the following AR Foundation versions:

* 5.0.6 ([changelog](https://docs.unity3d.com/Packages/com.unity.xr.arcore@5.0/changelog/CHANGELOG.html))
* 4.2.8 (docs haven't been published at time of writing, but the package is live)

A fix for 5.1 will go live in 5.1.0-pre.5 along with several new features in the coming weeks.

As always when upgrading AR Foundation versions, make sure that you upgrade ALL AR Foundation-related packages to the same version:

* com.unity.xr.arfoundation
* com.unity.xr.arcore
* com.unity.xr.arkit
* com.unity.xr.arsubsystems (AR Foundation 4.2 and below only)
* com.unity.xr.arkit-face-tracking (AR Foundation 4.2 and below only)

Please upgrade to the latest patch of your choice and let us know how it goes.

**Comment by DoppelG92** [comment] 2023-06-18 20:01
Thank you. I can confirm, that the bug is fixed. :)

**Comment by andyb-unity** [comment] 2023-06-21 18:36
Closing this issue as fixed. Feel free to re-open it if you discover any issues with the patch.

**Closed by andyb-unity** 2023-06-21 18:36 UTC
Labels: bug, fixed

**Comment by chandroidx** [comment] 2023-07-13 03:36
When I export and merge into Android project after upgrade to 5.0.6 , 
Error has been discovered that did not exist in verison 4.2.8.

EntryPointNotFoundException: Unable to find an entry point named 'UnityARCore_pointCloud_Create' in 'UnityARCore'. Tried the following entry points: Unable to get function 'UnityARCore_pointCloud_Create' because of 'The requested function was not found (0x06000001) dlerror() = undefined symbol: UnityARCore_pointCloud_Create
                                                                      at UnityEngine.XR.ARCore.ARCoreXRPointCloudSubsystem+ARCoreProvider.UnityARCore_pointCloud_Create (System.Func`1[TResult] guidGenerator) [0x00000] in <00000000000000000000000000000000>:0 
                                                                      at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00000] in <00000000000000000000000000000000>:0 
                                                                      at UnityEngine.SubsystemsImplementation.SubsystemDescriptorWithProvider`2[TSubsystem,TProvider].CreateProvider () [0x00000] in <00000000000000000000000000000000>:0 
                                                                      at UnityEngine.SubsystemsImplementation.SubsystemDescriptorWithProvider`2[TSubsystem,TProvider].Create () [0x00000] in <000000000000000000000000000

**Comment by chandroidx** [comment] 2023-07-13 03:37
When I export and merge into Android project after upgrade to 5.0.6 ,
�Error has been discovered that did not exist in verison 4.2.8.

EntryPointNotFoundException: Unable to find an entry point named 'UnityARCore_pointCloud_Create' in 'UnityARCore'. Tried the following entry points: Unable to get function 'UnityARCore_pointCloud_Create' because of 'The requested function was not found (0x06000001) dlerror() = undefined symbol: UnityARCore_pointCloud_Create
at UnityEngine.XR.ARCore.ARCoreXRPointCloudSubsystem+ARCoreProvider.UnityARCore_pointCloud_Create (System.Func1[TResult] guidGenerator) [0x00000] in <00000000000000000000000000000000>:0  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00000] in <00000000000000000000000000000000>:0  at UnityEngine.SubsystemsImplementation.SubsystemDescriptorWithProvider2[TSubsystem,TProvider].CreateProvider () [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.SubsystemsImplementation.SubsystemDescriptorWithProvider`2[TSubsystem,TProvider].Create () [0x00000] in <000000000000000000000000000

**Comment by andyb-unity** [comment] 2023-07-13 18:34
Hi @chandroidx,

EntryPointNotFoundExceptions are usually the result of a mismatch in version numbers. Please ensure that your version numbers are identical for both AR Foundation (com.unity.xr.arfoundation) and the Google ARCore XR Plug-in (com.unity.xr.arcore).
