### ISSUE TITLE
When using the recording feature the saved video doesnt show the point clouds generated while tracking[Bug]

### ISSUE THREAD

**Issue by shubhamguptak** [Unity-Technologies/arfoundation-samples#1007] opened 2022-09-20 17:54 UTC
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**
 When using the recording feature the saved video doesnt show the point clouds generated while tracking

**To Reproduce**
1. Build the android apk
2. Open Recording
3. Scan the area and see for point cloud
4. Check the saved video. The point cloud does not show up

**Expected behavior**
The recording should show the point cloud

**Actual behavior**
It did not

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11i hypercharge
 - OS: Android
 - Unity version - 2021
 - ARFoundation version 5

**Comment by DavidMohrhardt** [comment] 2022-09-20 22:05
Could you please provide a video of the issue you are seeing?

**Comment by andyb-unity** [comment] 2022-09-20 22:57
@shubhamguptak Also if you wouldn't mind following the instructions in the first sentence above, have you filed a bug? If so please post the case number here.

**Comment by andyb-unity** [comment] 2022-10-04 22:44
Upon revisiting this question, note that Google's ARSession Recording feature does not save any trackables. See Google's documentation for more information: https://developers.google.com/ar/develop/recording-and-playback#what%E2%80%99s_in_a_recording

For further questions you can follow up with Google here: https://github.com/google-ar/arcore-android-sdk

**Comment by tdmowrer** [comment] 2022-10-06 16:24
@shubhamguptak you wrote:

> Check the saved video. The point cloud does not show up

Were you watching the video in a regular mp4 movie player? This would only show the camera feed and nothing else (by design).

The ARCore session recorder records the camera feed as a regular mp4 video on the primary track and sensor data on other tracks. Trackables like the point cloud can be rediscovered when you play back the recording in an ARCore session on a compatible Android device, but, as @andyb-unity points out, the recording itself does not contain the point cloud. Note also that the results are nondeterministic, so you would not get exactly the same point cloud on subsequent runs.

If your intention is to record a video showing exactly what you see on screen, there are apps that can capture a screen recording. Is this what you're trying to do?

**Comment by shubhamguptak** [comment] 2022-10-06 17:04
Yes but then what's the point of adding a recording feature if it doesn't
capture the virtual objects overlayed on top of it.

**Comment by andyb-unity** [comment] 2022-10-06 17:38
Thanks for the clearer language, @tdmowrer! @shubhamguptak the session recording feature can be useful, as one example, in an automated testing context. You could record an AR Session in your desired physical space, then test future builds of your app using the recorded session rather than returning to that space for every test.

Screen recording is a different use case better served using other tools as Tim points out.

**Comment by ankur-unity** [comment] 2023-01-24 17:09
Closing this issue as it has been answered above. Feel free to reopen the issue for follow-up questions or open another issue.

**Closed by ankur-unity** 2023-01-24 17:09 UTC
Labels: bug
