### ISSUE TITLE
ARKit stops sending new frames in scene with Reflection Probe.

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/arfoundation-samples#216] opened 2019-07-20 06:48 UTC
Steps to reproduce:

1) Open the "HumanSegmentationImages" sample scene.
2) Add a new GameObject > Light > ReflectionProbe.
3) Set "Refresh Mode" to "Every Frame".
4) Build the project.
5) The scene will run for a few seconds, and then appear to freeze.

What is actually happening is that ARFoundation is not receiving any new frames. There are no error messages in Xcode, the app does not crash, everything else is working fine except that ARKit is no longer updating.

This code:

`unsafe void OnCameraFrameReceived(ARCameraFrameEventArgs eventArgs)
{
        Debug.Log(eventArgs.timestampNs.ToString());
}`

Still keeps receiving frames from ARFoundation. However it is the exact same frame with the same timestamp, same projection matrix, same pose, and same textures.

Reloading the scene does not change anything. The app has to be force quit in order for ARKit to work again.

Device: iPad Mini 5
Unity: 2019.1.2f1
OS: iPadOS 13 Beta 3 + 4
ARFoundation: 2.2.0 preview.3
ARKit XR Plugin: 2.2.0 preview.3
ARFoundation Samples: 07/19/2019

**Comment by sam598** [comment] 2019-07-20 07:03
Because there were no error messages, and ARFoundation was still sending updates as if nothing was wrong, it took a very long time to figure out what was wrong with my project.

It might have been easier to track down what was causing ARKit to break (and possible even fix it) if the ARKit library for ARFoundation was open source, like the original ARKit for Unity plugin was. Please see this issue for more information https://github.com/Unity-Technologies/arfoundation-samples/issues/190

**Comment by tdmowrer** [comment] 2019-10-09 02:53
> Because there were no error messages, and ARFoundation was still sending updates as if nothing was wrong, it took a very long time to figure out what was wrong with my project.

What ended up being the issue?

**Comment by sam598** [comment] 2019-10-09 03:49
I never found a way to solve the issue. It took a long time to find that it was the reflection probe that was causing ARKit to break.

It might have been resolved in a subsequent ARKit update but I haven't had time to test yet.

**Comment by tdmowrer** [comment] 2020-02-25 22:00
I was not able to reproduce this in the current version of this repo (using 3.1.0-preview.4 packages). I'll close this issue, but please [submit a bug](https://unity3d.com/unity/qa/bug-reporting) (and post the issue number here) if you see this again.

**Closed by tdmowrer** 2020-02-25 22:00 UTC
