### ISSUE TITLE
ios: Internal: JobTempAlloc leak - TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp

### ISSUE THREAD

**Issue by sergiosolorzano** [Unity-Technologies/arfoundation-samples#85] opened 2019-01-10 05:51 UTC
Hi friends,

In developing on arfoundation for ios I get fatal errors shown below. Eventually the app froze. The Apple review team also had this issue so I don't think it's hardware specific. 

Sample project to reproduce and log file below. 

Disabling shadows on lights solves it. Unexpected behaviour showed with directional or point lights I tested. Reducing shadow type quality (low) or gamma rendering color space didn't solve it.

I'm on Unity 2018.3.0b7, ARFoundation preview22, arcore plugin preview24, arkit plugin preview 20. Card Nvidia geforce gtx970. Previously occurred in december https://github.com/Unity-Technologies/arfoundation-samples/issues/67 . Happy to provide details you may need.

Can someone please shed some light what the issue maybe or how to debug it further to solve it?

Cheers, Sergio

**Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak** 
(Filename: ./Runtime/Allocator/ThreadsafeLinearAllocator.cpp Line: 372) 
To Debug, enable the define: TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp. This will output the callstacks of the leaked allocations 

Here sample project to reproduce. https://github.com/sergiosolorzano/ARFoundation_ios_bug.git

build log file (had it running for a minute then forced stop app): [logfile.docx](https://github.com/Unity-Technologies/arfoundation-samples/files/2743746/logfile.docx)

**Comment by tdmowrer** [comment] 2019-01-10 06:04
I've seen some reports of the `JobTempAlloc` memory leak, but they seem to be related to shadows or directional lighting, not ARFoundation specific.

The hang is a real problem which will be fixed in Unity 2018.3.4, probably around the end of this month.

**Comment by sergiosolorzano** [comment] 2019-01-10 06:06
Thank you @tdmowrer

**Comment by nilsk123** [comment] 2019-01-10 08:47
> Thank you for your comment @tdmowrer , one further question please - I tried running on 2019.1 but had this error at editor launch.
> 
> Library\PackageCache\com.unity.xr.arextensions@1.0.0-preview.7\Runtime\XRPlaneExtensions.cs(64,34): error CS0117: 'TrackingState' does not contain a definition for 'Unknown'
> Library\PackageCache\com.unity.xr.facesubsystem@1.0.0-preview.5\Runtime\XRFaceSubsystem.cs(125,34): error CS0117: 'TrackingState' does not contain a definition for 'Unknown'
> 
> Is ARFoundation supported on 2019 that would have solved it or any pointers to resolve the above? Trying to find another venue to use shadows before 2018.3.4 is released :)
> 
> Thank you for your help, Sergio

https://github.com/Unity-Technologies/arfoundation-samples/issues/79#issuecomment-450263059

**Comment by sergiosolorzano** [comment] 2019-01-10 19:23
OK @tdmowrer  thank you for your response, cheers, Sergio

**Comment by Sekamelica** [comment] 2019-10-02 15:30
Hi, I've got the same problem on iPad, with:
- Unity 2019.2.3f1,
- ARFoundation 2.1.3,
- ARCore XR Plugin 2.1.1,
- ARKit XR Plugin 2.1.1.
I can avoid the leak by deactivating shadows in quality settings, but I really need to have them. Have you find a way to keep them while avoiding the JobTempAlloc leak since @sergiosolorzano ?
If anyone has more informations about this bug or know a version of Unity where it doesn't happen, I would really like to know more about this. Thanks!

**Comment by sergiosolorzano** [comment] 2019-10-02 17:06
hey @Sekamelica I switched to lwrp and works fine in regards to leaks though you may find lwrp having its own limitations
Unity 2019.2.2, ARF 3.0.0 prev.2, lwrp 6.9.1

**Comment by tdmowrer** [comment] 2019-10-05 18:54
This is a known issue in Unity under active investigation and is not related to ARFoundation (it can be easily reproduced in a simple scene without ARFoundation). It is related to shadows in the legacy renderer so disabling shadows or switching to LWRP/UniversalRP should resolve the issue. And FWIW, I've only been able to reproduce it on older devices.

Closing issue as this is not related to AR.

**Closed by tdmowrer** 2019-10-05 18:54 UTC
